# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.cache/wt [current_project]
set_property parent.project_path /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.srcs/sources_1/ip/floating_point_0/floating_point_0.dcp
set_property used_in_implementation false [get_files /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.srcs/sources_1/ip/floating_point_0/floating_point_0.dcp]
add_files -quiet /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /csehome/cobaltblu27/HSD/project/verilog_project/verilog_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /csehome/cobaltblu27/HSD/project/HSD_LAB8/hw_2/pe.v
  /csehome/cobaltblu27/HSD/project/HSD_LAB8/hw_2/pe_controller.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top pe_con -part xc7z020clg484-1


write_checkpoint -force -noxdef pe_con.dcp

catch { report_utilization -file pe_con_utilization_synth.rpt -pb pe_con_utilization_synth.pb }
